name: QIL Validate + Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate repo
        run: |
          echo "Repo OK. (No build step needed for API-only project)"

  deploy_pages:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4

      - name: Create stub site
        run: |
          mkdir -p site
          cat > site/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>QIL</title>
          <h1>Quantum Intelligence Lattice</h1>
          <p>This repo hosts an API. See the Replit front-end for live endpoints.</p>
          HTML

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
