name: QIL Validate + Deploy

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  validate:
    name: Validate Manifest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run validator
        run: python validate_manifest.py

  deploy:
    name: Deploy to GitHub Pages
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site   # adjust if your index.html is elsewhere
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
