name: Dream Console Breath Cycle

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

jobs:
  breathe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (best effort)
        run: |
          python -m pip install --upgrade pip || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi

      - name: Exhale Breath Cycle
        run: |
          python - <<'PY'
          from core.breath_engine import take_breath
          p, _ = take_breath("Automated breath (GitHub Actions)")
          print(f"Wrote {p}")
          PY

      - name: Commit Breath Journal
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add codex/*.md
          git commit -m "Automated breath cycle" || echo "No changes"
          git push

      # Optional: notify QIL if hook URL/secret are set
      - name: Trigger QIL hook (optional)
        env:
          QIL_URL: ${{ secrets.QIL_URL }}
          QIL_SECRET: ${{ secrets.QIL_SECRET }}
        run: |
          if [ -n "$QIL_URL" ] && [ -n "$QIL_SECRET" ]; then
            latest_file=$(ls -t codex/cycle*.md | head -n1)
            curl -sS -X POST "$QIL_URL/hook" \
              -H "Content-Type: application/json" \
              -H "X-QIL-Secret: $QIL_SECRET" \
              -d "{\"source\":\"dream-console\",\"status\":\"breath complete\",\"file\":\"$latest_file\",\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}"
          else
            echo "QIL_URL/QIL_SECRET not set. Skipping hook."
          fi
